import type { AgentDef } from './types'

export const AGENTS: AgentDef[] = [
  {
    id: 'knoll',
    name: 'KNOLL',
    class: 'root',
    status: 'active',
    primaryColor: '#ef4444',
    glowColor: 'rgba(239,68,68,0.4)',
    borderColor: '#ef4444',
    role: 'Security Arbiter',
    tagline: 'Every request passes through me.',
    goals: [
      'Zero-trust enforcement across all agents',
      'Real-time threat detection and response',
      'Immutable audit trail for all operations',
    ],
    tools: ['supabase-rls', 'redis', 'cloudflare-waf', 'gvisor', 'sentry'],
    children: [
      { id: 'knoll-auth-guard',        name: 'Auth Guard',        role: 'Authentication',   description: 'JWT validation, OAuth flows, session lifecycle management',                status: 'active',  tools: ['supabase-auth', 'jose'] },
      { id: 'knoll-session-validator', name: 'Session Validator', role: 'Session Control',  description: 'Active session tracking, device fingerprinting, anomaly detection',       status: 'active',  tools: ['redis', 'fingerprint-js'] },
      { id: 'knoll-permission-matrix', name: 'Permission Matrix', role: 'RBAC Engine',      description: 'Role-based access control with dynamic capability grants',                status: 'active',  tools: ['casbin', 'zod'] },
      { id: 'knoll-threat-detector',   name: 'Threat Detector',   role: 'Threat Intel',     description: 'Real-time anomaly scoring, IP reputation, behavioral analysis',           status: 'active',  tools: ['axiom', 'ip-reputation-api'] },
      { id: 'knoll-audit-trail',       name: 'Audit Trail',       role: 'Compliance Log',   description: 'Immutable append-only log of every privileged action',                   status: 'active',  tools: ['supabase', 'litestream'] },
      { id: 'knoll-access-log',        name: 'Access Log',        role: 'Request Logger',   description: 'Per-request structured logging with latency and user context',            status: 'active',  tools: ['pino', 'cloudflare-logpush'] },
      { id: 'knoll-vault-keeper',      name: 'Vault Keeper',      role: 'Secret Management',description: 'Encrypted secrets rotation, API key vaulting, least-privilege access',   status: 'active',  tools: ['doppler', 'aws-kms'] },
      { id: 'knoll-supabase-rls',      name: 'Supabase RLS',      role: 'Row-Level Security',description: 'PostgreSQL RLS policies enforcing owner isolation at the DB layer',      status: 'active',  tools: ['supabase', 'pg-rls'] },
      { id: 'knoll-freeze-gate',       name: 'Freeze Gate',       role: 'Circuit Breaker',  description: 'Emergency freeze switch that halts all agent operations instantly',       status: 'standby', tools: ['upstash-redis', 'vercel-edge'] },
      { id: 'knoll-redis-cache',       name: 'Redis Cache',       role: 'Rate Limiter',     description: 'Token-bucket rate limiting and distributed session caching',              status: 'active',  tools: ['upstash-redis', 'ioredis'] },
      { id: 'knoll-legal-gates',       name: 'Legal Gates',       role: 'Compliance',       description: 'GDPR, CCPA, and ToS enforcement with automated data subject requests',   status: 'active',  tools: ['osano', 'termly'] },
      { id: 'knoll-tenancy-manager',   name: 'Tenancy Manager',   role: 'Multi-tenancy',    description: 'Workspace isolation, org-level billing caps, user provisioning',         status: 'active',  tools: ['supabase', 'stripe'] },
      { id: 'knoll-gvisor-sandbox',    name: 'gVisor Sandbox',    role: 'Isolation Runtime',description: 'Kernel-level sandboxing for untrusted code execution',                  status: 'idle',    tools: ['gvisor', 'docker'] },
      { id: 'knoll-observability',     name: 'Observability',     role: 'APM / Tracing',    description: 'Distributed tracing, error rates, latency histograms',                  status: 'active',  tools: ['sentry', 'axiom', 'opentelemetry'] },
      { id: 'knoll-prisma-guard',      name: 'Prisma Guard',      role: 'ORM Security',     description: 'Query sanitization, parameterization enforcement, schema drift alerts', status: 'active',  tools: ['prisma', 'zod'] },
      { id: 'knoll-cloudflare-waf',    name: 'Cloudflare WAF',    role: 'Edge Protection',  description: 'OWASP rule sets, bot scoring, DDoS mitigation at the edge',             status: 'active',  tools: ['cloudflare-waf', 'cf-workers'] },
      { id: 'knoll-sentry-monitor',    name: 'Sentry Monitor',    role: 'Error Tracking',   description: 'Production error capture, performance profiling, alert routing',        status: 'active',  tools: ['sentry', 'slack-webhook'] },
    ],
  },
  {
    id: 'hope',
    name: 'HOPE',
    class: 'persistent',
    status: 'active',
    primaryColor: '#8b5cf6',
    glowColor: 'rgba(139,92,246,0.4)',
    borderColor: '#8b5cf6',
    role: 'User Interface & Intent Layer',
    tagline: 'I speak to them. They speak through me.',
    goals: [
      'Render a living, responsive UI for every user persona',
      'Interpret intent and route it to APEX faithfully',
      'Maintain emotional continuity across sessions',
    ],
    tools: ['anthropic', 'livekit', 'posthog', 'matrix', 'nakama'],
    children: [
      { id: 'hope-intent-parser',       name: 'Intent Parser',       role: 'NLU',              description: 'Classifies user input into structured intents with confidence scores',        status: 'active', tools: ['anthropic', 'zod'] },
      { id: 'hope-persona-manager',     name: 'Persona Manager',     role: 'Identity',         description: 'Maintains per-user persona state, voice preferences, interaction history',  status: 'active', tools: ['supabase', 'zustand'] },
      { id: 'hope-ui-renderer',         name: 'UI Renderer',         role: 'Frontend Engine',  description: 'Dynamic React component tree driven by agent state',                        status: 'active', tools: ['react', 'framer-motion'] },
      { id: 'hope-conversation-buffer', name: 'Conversation Buffer', role: 'Context Window',   description: 'Sliding window context buffer with semantic compression',                   status: 'active', tools: ['anthropic', 'idb'] },
      { id: 'hope-context-weaver',      name: 'Context Weaver',      role: 'Memory Synthesis', description: 'Weaves long-term memory into active context for coherent sessions',          status: 'active', tools: ['supabase', 'pgvector'] },
      { id: 'hope-emotion-engine',      name: 'Emotion Engine',      role: 'Affective Layer',  description: 'Tracks user emotional state and adapts tone, pacing, and word choice',      status: 'active', tools: ['anthropic', 'posthog'] },
      { id: 'hope-narrative-voice',     name: 'Narrative Voice',     role: 'Storytelling',     description: 'Maintains consistent character voice across HOPE responses',                status: 'active', tools: ['anthropic', 'elevenlabs'] },
      { id: 'hope-anthropic-client',    name: 'Anthropic Client',    role: 'LLM Gateway',      description: 'Managed connection to Claude API with streaming, retries, and fallback',    status: 'active', tools: ['anthropic-sdk', 'vercel-ai'] },
      { id: 'hope-livekit-client',      name: 'LiveKit Client',      role: 'Voice/Video',      description: 'Real-time voice and video rooms for companion interactions',                status: 'idle',   tools: ['livekit-client', 'webrtc'] },
      { id: 'hope-posthog-analytics',   name: 'PostHog Analytics',   role: 'Product Analytics',description: 'Event capture, funnel analysis, feature flag delivery',                    status: 'active', tools: ['posthog-js', 'posthog-node'] },
      { id: 'hope-matrix-client',       name: 'Matrix Client',       role: 'Messaging',        description: 'Federated messaging via Matrix for team and user comms',                  status: 'idle',   tools: ['matrix-js-sdk'] },
      { id: 'hope-nakama-client',       name: 'Nakama Client',       role: 'Social Graph',     description: 'Real-time multiplayer, leaderboards, friends, and social features',        status: 'idle',   tools: ['nakama-js', 'heroiclabs'] },
      { id: 'hope-monaco-editor',       name: 'Monaco Editor',       role: 'Code IDE',         description: 'In-browser VS Code editor for user code creation and live editing',        status: 'active', tools: ['monaco-editor', 'vscode-languageserver'] },
      { id: 'hope-companion-memory',    name: 'Companion Memory',    role: 'Long-term Memory', description: 'Vector-indexed episodic memory recalled during companion sessions',         status: 'active', tools: ['pgvector', 'supabase'] },
      { id: 'hope-portrait-engine',     name: 'Portrait Engine',     role: 'Avatar Rendering', description: 'Dynamic character portrait generation and expression mapping',             status: 'active', tools: ['threejs', 'live2d'] },
      { id: 'hope-seo-engine',          name: 'SEO Engine',          role: 'Search Visibility',description: 'Metadata generation, sitemap management, structured data injection',       status: 'active', tools: ['next-seo', 'schema-org'] },
      { id: 'hope-brand-builder',       name: 'Brand Builder',       role: 'Identity Design',  description: 'AI-driven brand kit generation: logo, palette, typography, voice',          status: 'active', tools: ['anthropic', 'canva-api'] },
      { id: 'hope-market-research',     name: 'Market Research',     role: 'Competitive Intel',description: 'Automated market sizing, competitor analysis, and opportunity mapping',    status: 'active', tools: ['perplexity-api', 'airtable'] },
      { id: 'hope-landing-page-gen',    name: 'Landing Page Gen',    role: 'Conversion',       description: 'One-click landing page generation from idea to deployed URL',              status: 'active', tools: ['anthropic', 'vercel', 'tailwind'] },
    ],
  },
  {
    id: 'apex',
    name: 'APEX',
    class: 'persistent',
    status: 'active',
    primaryColor: '#06b6d4',
    glowColor: 'rgba(6,182,212,0.4)',
    borderColor: '#06b6d4',
    role: 'Orchestrator & Backend Router',
    tagline: 'Every agent obeys the chain.',
    goals: [
      'Route all tasks to the correct agent or tool',
      'Manage compute resources across ephemeral agents',
      'Maintain the canonical tool registry',
    ],
    tools: ['kafka', 'fastify', 'mistral', 'docker', 'github-actions'],
    children: [
      { id: 'apex-task-router',         name: 'Task Router',         role: 'Orchestration',    description: 'Routes incoming tasks to the correct agent based on capability and load',   status: 'active', tools: ['bullmq', 'zod'] },
      { id: 'apex-agent-spawner',       name: 'Agent Spawner',       role: 'Lifecycle Mgmt',   description: 'Spins up ephemeral agents on demand, tracks their state and teardown',      status: 'active', tools: ['docker', 'k8s'] },
      { id: 'apex-tool-registry',       name: 'Tool Registry',       role: 'Tool Catalog',     description: 'Canonical registry of all available tools with schemas and versions',       status: 'active', tools: ['supabase', 'zod'] },
      { id: 'apex-memory-core',         name: 'Memory Core',         role: 'Shared Memory',    description: 'Cross-agent shared memory store for context and state handoff',             status: 'active', tools: ['redis', 'pgvector'] },
      { id: 'apex-security-gate',       name: 'Security Gate',       role: 'Authz Proxy',      description: 'Validates every agent-to-agent call against KNOLL permission matrix',      status: 'active', tools: ['knoll-permission-matrix', 'jose'] },
      { id: 'apex-api-bridge',          name: 'API Bridge',          role: 'External APIs',    description: 'Unified proxy for all third-party API calls with auth, retry, and caching', status: 'active', tools: ['undici', 'upstash-redis'] },
      { id: 'apex-resource-allocator',  name: 'Resource Allocator',  role: 'Compute Budget',   description: 'Enforces per-user compute budgets and prioritizes task queues',             status: 'active', tools: ['bullmq', 'supabase'] },
      { id: 'apex-mistral-nodes',       name: 'Mistral Nodes',       role: 'Local LLM',        description: 'Mistral model routing for fast, private, cost-efficient inference',         status: 'active', tools: ['mistral-api', 'ollama'] },
      { id: 'apex-mcp-server',          name: 'MCP Server',          role: 'Protocol Hub',     description: 'Model Context Protocol server exposing tools to Claude and other LLMs',     status: 'active', tools: ['mcp-sdk', 'fastify'] },
      { id: 'apex-kafka-queue',         name: 'Kafka Queue',         role: 'Event Streaming',  description: 'High-throughput event bus for agent communication and audit streaming',     status: 'active', tools: ['kafkajs', 'upstash-kafka'] },
      { id: 'apex-model-router',        name: 'Model Router',        role: 'LLM Selection',    description: 'Smart model selection based on task type, cost, latency SLOs',             status: 'active', tools: ['anthropic', 'mistral', 'openai'] },
      { id: 'apex-node-matrix',         name: 'Node Matrix',         role: 'Agent Graph',      description: 'Live graph of all active agents, their connections and health status',      status: 'active', tools: ['xyflow', 'zustand'] },
      { id: 'apex-prisma-client',       name: 'Prisma Client',       role: 'ORM Layer',        description: 'Type-safe database access layer with migrations and query optimization',    status: 'active', tools: ['prisma', 'postgresql'] },
      { id: 'apex-fastify-gateway',     name: 'Fastify Gateway',     role: 'API Gateway',      description: 'High-performance REST/WebSocket gateway with plugin ecosystem',            status: 'active', tools: ['fastify', 'zod'] },
      { id: 'apex-byok-router',         name: 'BYOK Router',         role: 'Key Management',   description: 'Bring-your-own-key routing: user API keys used transparently',             status: 'active', tools: ['doppler', 'knoll-vault-keeper'] },
      { id: 'apex-vercel-deployer',     name: 'Vercel Deployer',     role: 'CD Pipeline',      description: 'Automated deployment pipeline with preview URLs and rollback',             status: 'active', tools: ['vercel-api', 'github-actions'] },
      { id: 'apex-github-actions',      name: 'GitHub Actions',      role: 'CI/CD',            description: 'CI/CD workflows: lint, test, build, deploy across all repos',              status: 'active', tools: ['github-api', 'act'] },
      { id: 'apex-cloudflare-edge',     name: 'Cloudflare Edge',     role: 'Edge Compute',     description: 'Workers, KV, R2, and D1 for edge-distributed workloads',                   status: 'active', tools: ['wrangler', 'cf-workers'] },
      { id: 'apex-docker-orchestrator', name: 'Docker Orchestrator', role: 'Container Mgmt',   description: 'Container lifecycle, health checks, secrets injection, and scaling',       status: 'active', tools: ['docker', 'compose', 'k8s'] },
    ],
  },
  {
    id: 'dream',
    name: 'DREAM',
    class: 'ephemeral',
    status: 'idle',
    primaryColor: '#d946ef',
    glowColor: 'rgba(217,70,239,0.4)',
    borderColor: '#d946ef',
    role: 'Creation & Simulation Engine',
    tagline: 'I build the impossible. Then I disappear.',
    goals: [
      'Generate worlds, assets, and simulations on demand',
      'Synthesize media: audio, video, 3D, and narrative',
      'Run chaos testing and physics simulations',
    ],
    tools: ['google-ai-studio', 'elevenlabs', 'runway-ml', 'figma', 'colab'],
    children: [
      { id: 'dream-world-builder',     name: 'World Builder',     role: 'World Gen',        description: 'Procedural world generation with biomes, lore, and faction systems',       status: 'idle', tools: ['anthropic', 'supabase'] },
      { id: 'dream-scene-composer',    name: 'Scene Composer',    role: 'Scene Design',     description: 'Composes visual scenes from prompts using generative image models',        status: 'idle', tools: ['google-imagen', 'flux'] },
      { id: 'dream-entity-generator',  name: 'Entity Generator',  role: 'NPC/Character',    description: 'Generates fully realized characters with backstory, traits, and voice',    status: 'idle', tools: ['anthropic', 'elevenlabs'] },
      { id: 'dream-physics-simulator', name: 'Physics Simulator', role: 'Simulation',       description: 'Deterministic physics sim for game worlds and chaos testing',              status: 'idle', tools: ['matter-js', 'rapier'] },
      { id: 'dream-chaos-seed',        name: 'Chaos Seed',        role: 'Chaos Engineering',description: 'Injects controlled failures to test system resilience',                   status: 'idle', tools: ['chaos-monkey', 'k6'] },
      { id: 'dream-narrative-forge',   name: 'Narrative Forge',   role: 'Story Engine',     description: 'Branching narrative generation with memory-aware continuity',             status: 'idle', tools: ['anthropic', 'inkle-ink'] },
      { id: 'dream-asset-synthesizer', name: 'Asset Synthesizer', role: 'Asset Pipeline',   description: 'End-to-end game asset pipeline: concept → 3D → rigged → exported',       status: 'idle', tools: ['blender-api', 'meshy-ai'] },
      { id: 'dream-google-ai-studio',  name: 'Google AI Studio',  role: 'Gemini Gateway',   description: 'Gemini Pro/Flash models for vision, audio, and multimodal tasks',         status: 'idle', tools: ['gemini-api', 'google-cloud'] },
      { id: 'dream-colab-image',       name: 'Colab Image',       role: 'Image Generation', description: 'Stable Diffusion, FLUX, and ControlNet pipelines on Colab GPU',           status: 'idle', tools: ['google-colab', 'diffusers'] },
      { id: 'dream-colab-video',       name: 'Colab Video',       role: 'Video Generation', description: 'Video diffusion and motion synthesis on Colab A100 nodes',                status: 'idle', tools: ['google-colab', 'wan-video'] },
      { id: 'dream-kokoro-tts',        name: 'Kokoro TTS',        role: 'Text-to-Speech',   description: 'Local high-quality TTS with voice cloning support',                      status: 'idle', tools: ['kokoro-tts', 'onnx'] },
      { id: 'dream-ollama-local',      name: 'Ollama Local',      role: 'Local LLM',        description: 'On-device LLM inference for offline and private workloads',               status: 'idle', tools: ['ollama', 'llama3'] },
      { id: 'dream-vllm-server',       name: 'vLLM Server',       role: 'High-throughput LLM', description: 'PagedAttention-based LLM serving for batch inference',                 status: 'idle', tools: ['vllm', 'cuda'] },
      { id: 'dream-phaser-engine',     name: 'Phaser Engine',     role: '2D Game Runtime',  description: '2D game rendering and physics via Phaser 4',                             status: 'idle', tools: ['phaser', 'matter-js'] },
      { id: 'dream-threejs-3d',        name: 'Three.js 3D',       role: '3D Renderer',      description: 'WebGL-powered 3D scene rendering with post-processing effects',           status: 'idle', tools: ['threejs', 'r3f'] },
      { id: 'dream-elevenlabs',        name: 'ElevenLabs',        role: 'Voice Synthesis',  description: 'High-fidelity voice cloning and multi-lingual speech synthesis',          status: 'idle', tools: ['elevenlabs-api'] },
      { id: 'dream-runway-ml',         name: 'Runway ML',         role: 'Video AI',         description: 'Gen-3 video generation, inpainting, and motion brush tools',              status: 'idle', tools: ['runway-api'] },
      { id: 'dream-figma-api',         name: 'Figma API',         role: 'Design Handoff',   description: 'Programmatic Figma file creation, component export, and design sync',     status: 'idle', tools: ['figma-api', 'figma-mcp'] },
      { id: 'dream-canva-api',         name: 'Canva API',         role: 'Template Design',  description: 'Branded template generation and bulk design export via Canva',            status: 'idle', tools: ['canva-connect-api'] },
    ],
  },
  {
    id: 'vision',
    name: 'VISION',
    class: 'ephemeral',
    status: 'idle',
    primaryColor: '#f59e0b',
    glowColor: 'rgba(245,158,11,0.4)',
    borderColor: '#f59e0b',
    role: 'Execution & Automation Engine',
    tagline: 'Ideas land in reality through me.',
    goals: [
      'Execute autonomous tasks end-to-end',
      'Process payments and manage subscriptions',
      'Drive products from concept to market',
    ],
    tools: ['stripe', 'livekit-server', 'nakama', 'hubspot', 'docusign'],
    children: [
      { id: 'vision-task-executor',      name: 'Task Executor',      role: 'Autonomous Exec',  description: 'Runs multi-step agentic tasks with tool use and self-correction',          status: 'idle', tools: ['anthropic', 'bullmq'] },
      { id: 'vision-payment-processor',  name: 'Payment Processor',  role: 'Payments',         description: 'Stripe integration: charges, subscriptions, invoices, disputes',           status: 'idle', tools: ['stripe', 'supabase'] },
      { id: 'vision-automation-runner',  name: 'Automation Runner',  role: 'Workflow Engine',  description: 'Executes n8n/Zapier-style workflow automations triggered by events',       status: 'idle', tools: ['n8n', 'zapier'] },
      { id: 'vision-webhook-manager',    name: 'Webhook Manager',    role: 'Event Ingestion',  description: 'Receives, validates, and routes inbound webhooks from external services',  status: 'idle', tools: ['svix', 'zod'] },
      { id: 'vision-scheduler-daemon',   name: 'Scheduler Daemon',   role: 'Cron Jobs',        description: 'Manages scheduled jobs: digests, billing checks, data syncs',             status: 'idle', tools: ['cron', 'supabase'] },
      { id: 'vision-output-streamer',    name: 'Output Streamer',    role: 'SSE / WebSocket',  description: 'Streams agent output to the frontend in real-time via SSE',               status: 'idle', tools: ['vercel-ai', 'readablestream'] },
      { id: 'vision-audit-logger',       name: 'Audit Logger',       role: 'Execution Audit',  description: 'Structured logs for every automated action taken by VISION',              status: 'idle', tools: ['axiom', 'pino'] },
      { id: 'vision-stripe-connect',     name: 'Stripe Connect',     role: 'Marketplace',      description: 'Multi-party payments, creator payouts, and platform fees via Connect',    status: 'idle', tools: ['stripe-connect'] },
      { id: 'vision-stripe-identity',    name: 'Stripe Identity',    role: 'KYC / Verify',     description: 'Document and ID verification for high-value transactions',                status: 'idle', tools: ['stripe-identity'] },
      { id: 'vision-creator-market',     name: 'Creator Market',     role: 'Marketplace',      description: 'Creator economy: digital goods, licensing, revenue splits',               status: 'idle', tools: ['stripe-connect', 'supabase'] },
      { id: 'vision-livekit-server',     name: 'LiveKit Server',     role: 'Media Server',     description: 'Self-hosted LiveKit SFU for real-time voice, video, and data rooms',      status: 'idle', tools: ['livekit-server', 'docker'] },
      { id: 'vision-nakama-server',      name: 'Nakama Server',      role: 'Game Backend',     description: 'Authoritative game server: matchmaking, leaderboards, social graph',      status: 'idle', tools: ['nakama', 'cockroachdb'] },
      { id: 'vision-billing-meter',      name: 'Billing Meter',      role: 'Usage Billing',    description: 'Metered billing: tracks token usage, compute time, and API calls',        status: 'idle', tools: ['stripe-metered', 'supabase'] },
      { id: 'vision-sea-scyte-api',      name: 'Sea Scyte API',      role: 'Internal API',     description: 'Interface to the Sea Scyte analytics and telemetry service',              status: 'idle', tools: ['sea-scyte', 'fastify'] },
      { id: 'vision-resource-monitor',   name: 'Resource Monitor',   role: 'Infrastructure',   description: 'CPU, memory, latency, and cost monitoring across all deployments',        status: 'idle', tools: ['axiom', 'grafana'] },
      { id: 'vision-pitch-deck-forge',   name: 'Pitch Deck Forge',   role: 'Fundraising',      description: 'AI-generated investor pitch decks with market data and financials',       status: 'idle', tools: ['anthropic', 'canva-api', 'google-slides'] },
      { id: 'vision-hubspot-crm',        name: 'HubSpot CRM',        role: 'CRM',              description: 'Lead tracking, deal pipeline, and email sequences via HubSpot',          status: 'idle', tools: ['hubspot-api'] },
      { id: 'vision-docusign',           name: 'DocuSign',           role: 'eSignature',       description: 'Contract generation, sending, and signature tracking via DocuSign',      status: 'idle', tools: ['docusign-api'] },
      { id: 'vision-resend-email',       name: 'Resend Email',       role: 'Transactional Email', description: 'Developer-first transactional email with React templates',            status: 'idle', tools: ['resend-api', 'react-email'] },
      { id: 'vision-mailchimp',          name: 'Mailchimp',          role: 'Email Marketing',  description: 'Audience management, campaign automation, and analytics',                status: 'idle', tools: ['mailchimp-api'] },
      { id: 'vision-twitter-api',        name: 'Twitter / X API',    role: 'Social Media',     description: 'Post scheduling, analytics, and engagement automation on X',             status: 'idle', tools: ['twitter-api-v2'] },
      { id: 'vision-linkedin-api',       name: 'LinkedIn API',       role: 'Professional Net', description: 'Content publishing, lead gen, and company page management',              status: 'idle', tools: ['linkedin-api'] },
      { id: 'vision-cal-com',            name: 'Cal.com',            role: 'Scheduling',       description: 'Meeting booking, availability sync, and calendar automation',            status: 'idle', tools: ['cal-com-api'] },
      { id: 'vision-google-ads',         name: 'Google Ads',         role: 'Paid Acquisition', description: 'Campaign creation, bidding strategy, and conversion tracking',           status: 'idle', tools: ['google-ads-api'] },
      { id: 'vision-airtable',           name: 'Airtable',           role: 'Data & Ops',       description: 'Structured operational data, project tracking, and no-code automations', status: 'idle', tools: ['airtable-api'] },
    ],
  },
]

export function getAgent(id: string): AgentDef | undefined {
  return AGENTS.find(a => a.id === id)
}

export function getChildNode(id: string): { child: AgentDef['children'][0]; agent: AgentDef } | undefined {
  for (const agent of AGENTS) {
    const child = agent.children.find(c => c.id === id)
    if (child) return { child, agent }
  }
  return undefined
}
